let instagrammer = [
    {
        "name": "Stallone",
        "img": "img/img-stallone.jpg",
        "profile-img": "img/profile-stallone.jpg",
        "url": "https://www.instagram.com/officialslystallone/",
        "likes": 117543,
        "post": "Coming soon! #TULSA KING",
        "comments": ["michaelkirkdouglas: Looks great @officialslystallone!", "james gunn: Can't wait!"],
        "like": "img/heart-empty.png",
    },
    {
        "name": "Cyberpunk",
        "img": "img/img-cyberpunk.webp",
        "profile-img": "img/profile-cyberpunk.jpg",
        "url": "https://www.instagram.com/cyberpunkgame/",
        "likes": 43.345,
        "post": "Thank you for choosing #Cyberpunk2077 as the Labor of Love winner in the latest #SteamAwards!",
        "comments": ["Orchamedes: Love this game and love all the work that has gone into it since launch!", "Kovalcyk: Well deserved ♥️"],
        "like": "img/heart-empty.png",
    },
    {
        "name": "Schwarzenegger",
        "img": "img/img-Schwarzenegger.jpg",
        "profile-img": "img/profile-arnold.jpg",
        "url": "https://www.instagram.com/schwarzenegger/",
        "likes": 88.538,
        "post": "This week's #pumpdaily workout challenge. Sign up at the link in bio.",
        "comments": ["drevanantin: Yooooo🦾😆", "eva_divinia: My Hero 😍❤️"],
        "like": "img/heart-empty.png",
    },
    {
        "name": "TheRock",
        "img": "img/img-therock.jpg",
        "profile-img": "img/profile-rock.jpg",
        "url": "https://www.instagram.com/therock/",
        "likes": 353.432,
        "post": "Oh you want a selfie with me? I'd love to…🤳🏾 😍",
        "comments": ["jamesjeff: Moms said you gonna have to learn a simple 2-step before you take a picture with my son 😂😂", "moamer: Incredible!"],
        "like": "img/heart-empty.png",
    },
    {
        "name": "Santa Monica",
        "img": "img/img-santa.jpg",
        "profile-img": "img/profile-santa.jpg",
        "url": "https://www.instagram.com/santamonicastudio/",
        "likes": 1.337,
        "post": "To close out an incredible 2022, we want to highlight a selection of photos our VGP community has captured so far in #GodofWarRagnarok!",
        "comments": ["turbo453: I wish this game had a 3rd. I don't care if it took 10 years. Take my money.", "loganrussel: I'm calling this right now Fay soul is inside the Leviathan axe"],
        "like": "img/heart-empty.png",
    },
    {
        "name": "FC Bayern",
        "img": "img/img-bayern.jpeg",
        "profile-img": "img/profile-bayern.jpg",
        "url": "https://www.instagram.com/fcbayern/",
        "likes": 95.322,
        "post": "Home Sweet Home 🏟 We are back! 😍",
        "comments": ["naurice: GOOD LUCK BOYS💪 #miasanmia", "Bayernfan: All the best for the first Home Game in 2023"],
        "like": "img/heart-empty.png",
    },
    {
        "name": "CD-Projekt",
        "img": "img/img-cdprojekt.jpg",
        "profile-img": "img/profile-cdprojekt.jpg",
        "url": "https://www.instagram.com/cdpred/",
        "likes": 85.132,
        "post": "Over 20 million cyberpunks have been roaming the streets of Night City. Thank you and we hope to see you all in the Afterlife!",
        "comments": ["mauno: This game is awesome, I just want to stay in Night City forever! ❤️ Thank you for making this game so great", "zady.apo: Well deserved, many people were sleeping on this excellent experience! Time to party like it's 2023 "],
        "like": "img/heart-empty.png",
    },
    {
        "name": "GerardButler",
        "img": "img/img-gerard.jpg",
        "profile-img": "img/profile-gerard.jpg",
        "url": "https://www.instagram.com/gerardbutler/",
        "likes": 55.323,
        "post": "You. Me. #PlaneMovie. TOMORROW! Had the best time at our premiere and now it's your turn! Do you have your tickets?",
        "comments": ["planemovie: Don't mind the turbulence.", "Wondersewoow: Ohhh gerard ur looking great and I'm sure u have smashed it 🔥🔥👏❤️❤️"],
        "like": "img/heart-empty.png",
    },
    {
        "name": "HughJackman",
        "img": "img/img-hugh.jpg",
        "profile-img": "img/profile-hugh.jpg",
        "url": "https://www.instagram.com/thehughjackman/",
        "likes": 78.466,
        "post": "It was only a matter of time. The 2023 bloopers season begins. Welcome!",
        "comments": ["veselkadi: So beautiful 🤩😍🙌", "mariamoo: Been 5 days and you haven't posted. missed you."],
        "like": "img/heart-empty.png",
    },
];
